-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/dareum/anaconda3/envs/mujoco_py/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 1.3.8 (/opt/ros/humble/share/ament_cmake/cmake)
-- Found Python3: /home/dareum/anaconda3/envs/mujoco_py/bin/python3 (found version "3.8.19") found components: Interpreter 
-- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found geometry_msgs: 4.2.3 (/opt/ros/humble/share/geometry_msgs/cmake)
[31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/home/dareum/anaconda3/envs/mujoco_py/bin/python3 -m
  rosidl_adapter --package-name coin_rolling_msg --arguments-file
  /home/dareum/ME454/ros2_ws/build/coin_rolling_msg/rosidl_adapter__arguments__coin_rolling_msg.json
  --output-dir
  /home/dareum/ME454/ros2_ws/build/coin_rolling_msg/rosidl_adapter/coin_rolling_msg
  --output-file
  /home/dareum/ME454/ros2_ws/build/coin_rolling_msg/rosidl_adapter/coin_rolling_msg.idls)
  returned error code 1:

  Traceback (most recent call last):

    File "/home/dareum/anaconda3/envs/mujoco_py/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/dareum/anaconda3/envs/mujoco_py/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 18, in convert_to_idl
      from rosidl_adapter.msg import convert_msg_to_idl
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 16, in <module>
      from rosidl_adapter.resource import expand_template
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 19, in <module>
      import em

  ModuleNotFoundError: No module named 'em'

Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:23 (rosidl_generate_interfaces)

[0m
-- Configuring incomplete, errors occurred!
See also "/home/dareum/ME454/ros2_ws/build/coin_rolling_msg/CMakeFiles/CMakeOutput.log".
